name: ESLint

on:
  pull_request:
    branches:
      - main
      - develop

env: # environment variables (available in any part of the action)
  NODE_VERSION: 18

jobs:
  eslint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint
